  automation:
  ### heat pump cycling counter ############################
  ####### the initial values for the cycling must be taken once from the Lambda heat pump and entered into the sensor.
  - id: '1727726999508'
    alias: increment HP Timings
    description: Tacktungen der WP hochzählen
    trigger:
    - platform: state 
      entity_id:
      - sensor.eu08l_hp1_operating_state
      to: '1'
      id: Heating
    - platform: state
      entity_id:
      - sensor.eu08l_hp1_operating_state
      to: '2'
      id: HotWater
    condition: []
    action:
    - choose:
      - conditions:
        - condition: trigger
          id:
          - Heating
        sequence:
        - action: counter.increment
          metadata: {}
          data: {}
          target:
            entity_id:
            - counter.eu8l_heat_pump_cycling_diff
            - counter.eu8l_heat_pump_cycling_daily
      - conditions:
        - condition: trigger
          id:
          - HotWater
        sequence:
        - action: counter.increment
          metadata: {}
          data: {}
          target:
            entity_id:
            - counter.eu08l_hot_water_cycling_diff
            - counter.eu08l_hot_water_cycling_daily
    mode: single
  - id: '1727727092095'
    alias: reset counter for daily HP timing
    description: Zähler für daily tacktung WP resetten
    trigger:
    - platform: time
      at: 00:00:00
    condition: []
    action:
    - action: counter.reset
      metadata: {}
      data: {}
      target:
        entity_id:
        - counter.eu8l_heat_pump_cycling_daily
        - counter.eu08l_hot_water_cycling_daily
    mode: single
  
  - id: '1728482010496'
    alias: kWh HotWater
    description: ''
    triggers:
    - trigger: state
      entity_id:
      - sensor.eu08l_hp1_operating_state
      from: '2'
      id: from2
    - trigger: state
      entity_id:
      - sensor.eu08l_hp1_operating_state
      id: to2
      to: '2'
    conditions: []
    actions:
    - choose:
      - conditions:
        - condition: trigger
          id:
          - to2
        sequence:
        - action: input_number.set_value
          metadata: {}
          data:
            value: '{{states(''sensor.eu08l_hp1_compressor_power_consumption_accumulated'')
              | float(0) /1000}}'
          target:
            entity_id: input_number.eu08l_energy_hot_water_start
      - conditions:
        - condition: trigger
          id:
          - from2
        sequence:
        - action: input_number.set_value
          metadata: {}
          data:
            value: '{{states(''sensor.eu08l_hp1_compressor_power_consumption_accumulated'')
              | float(0) /1000}}'
          target:
            entity_id: input_number.eu08l_energy_hot_water_end
        - action: input_number.set_value
          metadata: {}
          data:
            value: '{{states(''input_number.eu08l_energy_hot_water_sum'') | float(0) + (states(''input_number.eu08l_energy_hot_water_end'')
              |float(0) - states(''input_number.eu08l_energy_hot_water_start'') |float(0)
              ) | float(0)}}'
          target:
            entity_id: input_number.eu08l_energy_hot_water_sum
    mode: single
  - id: '1728483475534'
    alias: Heating kWh
    description: ''
    triggers:
    - trigger: state
      entity_id:
      - sensor.eu08l_hp1_operating_state
      from: '1'
      id: from2
    - trigger: state
      entity_id:
      - sensor.eu08l_hp1_operating_state
      id: to2
      to: '1'
    conditions: []
    actions:
    - choose:
      - conditions:
        - condition: trigger
          id:
          - to2
        sequence:
        - action: input_number.set_value
          metadata: {}
          data:
            value: '{{states(''sensor.eu08l_hp1_compressor_power_consumption_accumulated'')
              | float(0) /1000}}'
          target:
            entity_id: input_number.eu08l_energy_heating_start
      - conditions:
        - condition: trigger
          id:
          - from2
        sequence:
        - action: input_number.set_value
          metadata: {}
          data:
            value: '{{states(''sensor.eu08l_hp1_compressor_power_consumption_accumulated'')
              | float(0) /1000}}'
          target:
            entity_id: input_number.eu08l_energy_heating_end
        - action: input_number.set_value
          metadata: {}
          data:
            value: '{{states(''input_number.eu08l_energy_heating_sum'') | float(0) + (states(''input_number.eu08l_energy_heating_end'')
              |float(0) - states(''input_number.eu08l_energy_heating_start'') |float(0)
              ) | float(0)}}'
          target:
            entity_id: input_number.eu08l_energy_heating_sum
    mode: single
  