  automation:
  - id: '1727726999508'
    alias: increment HP Timings
    description: Taktungen der WP hochzählen
    mode: single
    triggers:
      - entity_id:
          - sensor.eu08l_hp1_operating_state
        to: "1"
        id: Heating
        trigger: state
      - entity_id:
          - sensor.eu08l_hp1_operating_state
        to: "2"
        id: HotWater
        trigger: state
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Heating
            sequence:
              - action: counter.increment
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - counter.eu08l_heat_pump_cycling
                    - counter.eu08l_heat_pump_cycling_daily
          - conditions:
              - condition: trigger
                id:
                  - HotWater
            sequence:
              - action: counter.increment
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - counter.eu08l_hot_water_cycling
                    - counter.eu08l_hot_water_cycling_daily
    
  - id: '1727727092095'
    alias: reset counter for daily HP timing
    description: Zähler für daily tacktung WP resetten
    triggers:
    - at: 00:00:00
      trigger: time
    conditions: []
    actions:
    - action: counter.reset
      metadata: {}
      data: {}
      target:
        entity_id:
        - counter.eu8l_heat_pump_cycling_daily
        - counter.eu08l_hot_water_cycling_daily
    mode: single
  - id: '6543235'
    alias: set Lambda Raumtemp
    description: ''
    triggers:
    - minutes: /5
      trigger: time_pattern
      enabled: false
    - entity_id:
      - sensor.thermometer_wohnzimmer_temperature
      trigger: state
    conditions: []
    actions:
    - data:
        hub: EU08L
        address: 5004
        value:
        - '{{ (float(states(''sensor.thermometer_wohnzimmer_temperature'')) *10 ) |round(0)  }}'
      action: modbus.write_register
    mode: single
