counter:
## to monitor the heat pump's cycling, here are the sensors.
## you have to take the initial values from the lambda
  eu08l_heat_pump_cycling_start:
    name: eu08l_heat_pump_cycling_start
    initial: 27
  eu08l_hot_water_cycling_start:
    name: eu08l_hot_water_cycling_start
    initial: 105
## here are the counters for the daily cyceling, 
## they are increased via the automation when the Lambda sets the sensor “sensor.eu08l_hp1_operating_state” to 1 = heating or 2 = hot water
  eu8l_heat_pump_cycling_daily:
    name: eu08l_heat_pump_cycling_daily
    initial: 0

  eu08l_hot_water_cycling_daily:
    name: eu8l_hot_water_cycling_daily
    initial: 0
  ## here the counter for total cyceling values. they will also be incresed as the daily cyceling counter
  eu8l_heat_pump_cycling_diff:
    name: eu08l_heat_pump_cycling_diff
    initial: 0

  eu08l_hot_water_cycling_diff:
    name: eu8l_hot_water_cycling_diff
    initial: 0
# In order to show total cyceling values in the dashboard and to persist them in the DB, we have to add the cyceling_start & cyceleing_diff Values 
sensor:
  - platform: template
    sensors:
      eu08l_hot_water_cycling:
        friendly_name: "eu08l_hot_water_cycling"
        value_template: >
          {% set count1 = states('counter.eu08l_hot_water_cycling_start') | int(0) %}
          {% set count2 = states('counter.eu8l_hot_water_cycling_diff') | int(0) %}
          {{ count1 + count2 }}
  - platform: template
    sensors:
      eu08l_heat_pump_cycling:
        friendly_name: "eu08l_heat_pump_cycling"
        value_template: >
          {% set count1 = states('counter.eu08l_heat_pump_cycling_start') | int(0) %}
          {% set count2 = states('counter.eu08l_heat_pump_cycling_diff') | int(0) %}
          {{ count1 + count2 }}


input_number:
  eu08l_energy_hot_water_sum:
    name: "energy_hot_water_sum"
    step: 0.1
    min: 0
    max: 9999999
    unit_of_measurement: "kWh"
  eu08l_energy_hot_water_start:
    name: "energy_hot_water_start"
    step: 0.1
    min: 0
    max: 9999999
    initial: 0
    unit_of_measurement: "kWh"
  eu08l_energy_hot_water_end:
    name: "energy_hot_water_end"
    step: 0.1
    min: 0
    max: 9999999
    initial: 0
    unit_of_measurement: "kWh"
##### Heating Enery Consumption
  eu08l_energy_heating_sum:
    name: "energy_heating_sum"
    step: 0.1
    min: 0
    max: 9999999
    unit_of_measurement: "kWh"
  eu08l_energy_heating_start:
    name: "energy_heating_start"
    step: 0.1
    min: 0
    max: 9999999
    initial: 0
    unit_of_measurement: "kWh"
  eu08l_energy_heating_end:
    name: "energy_heating_end"
    step: 0.1
    min: 0
    max: 9999999
    initial: 0
    unit_of_measurement: "kWh"

