  automation:
  ### heat pump cycling counter ############################
  ####### the initial values for the cycling must be taken once from the Lambda heat pump and entered into the sensor.
  - id: '1727726999508'
    alias: increment HP Timings
    description: Tacktungen der WP hochzählen
    trigger:
    - platform: state 
      entity_id:
      - sensor.eu08l_hp1_operating_state
      to: '1'
      id: Heating
    - platform: state
      entity_id:
      - sensor.eu08l_hp1_operating_state
      to: '1'
      id: HotWater
    condition: []
    action:
    - choose:
      - conditions:
        - condition: trigger
          id:
          - Heating
        sequence:
        - action: counter.increment
          metadata: {}
          data: {}
          target:
            entity_id:
            - counter.eu08l_heat_pump_cycling
            - counter.eu8l_heat_pump_cycling_daily
      - conditions:
        - condition: trigger
          id:
          - HotWater
        sequence:
        - action: counter.increment
          metadata: {}
          data: {}
          target:
            entity_id:
            - counter.eu08l_hot_water_cycling
            - counter.eu08l_hot_water_cycling_daily
    mode: single
  - id: '1727727092095'
    alias: reset counter for daily HP timing
    description: Zähler für daily tacktung WP resetten
    trigger:
    - platform: time
      at: 00:00:00
    condition: []
    action:
    - action: counter.reset
      metadata: {}
      data: {}
      target:
        entity_id:
        - counter.eu8l_heat_pump_cycling_daily
        - counter.eu08l_hot_water_cycling_daily
    mode: single
  