sensor:  
  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_abstellkeller_temperature
    indoor_humidity_sensor: sensor.thermometer_abstellkeller_humidity
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Abstellkeller

  - platform: mold_indicator
    indoor_temp_sensor: sensor.0x28dba7fffe0792d8_temperature
    indoor_humidity_sensor: sensor.0x28dba7fffe0792d8_humidity
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Abstellraum

  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_gastezimmer_temperatur
    indoor_humidity_sensor: sensor.thermometer_gastezimmer_luftfeuchtigkeit
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Gaestezimmer

  - platform: mold_indicator
    indoor_temp_sensor: sensor.bad_1og
    indoor_humidity_sensor: sensor.meter_5e55_luftfeuchtigkeit
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Bad 1OG

  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_2og_bad_temperatur
    indoor_humidity_sensor: sensor.thermometer_2og_bad_luftfeuchtigkeit
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Bad 2OG

  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_schlafzimmer_temperature
    indoor_humidity_sensor: sensor.thermometer_schlafzimmer_humidity
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Schlafzimmer
    
  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_wohnzimmer_temperature
    indoor_humidity_sensor: sensor.thermometer_wohnzimmer_humidity
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Wohnzimmer
    
  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_vitrine_wohnzimmer_haus
    indoor_humidity_sensor: sensor.thermometer_vitrine_wohnzimmer_humidity
    outdoor_temp_sensor: sensor.indoor_outdoor_meter_5024
    calibration_factor: 2.0
    name: Schimmel Wohnzimmer Vitrine

  - platform: mold_indicator
    indoor_temp_sensor: sensor.thermometer_wohnzimmer_temperature
    indoor_humidity_sensor: sensor.thermometer_wohnzimmer_humidity
    outdoor_temp_sensor: sensor.thermometer_wohnzimmer_temperature
    calibration_factor: 2.0
    name: Schimmel Treppenhaus 2OG
  