#####

#### Helper   ################################
input_number:
  zaehlerstand:
  ## helper um den aktuellen Zählerstand berechnen zu können (dieser Helper+total import)
    name: Zählerstand helper
    initial: 50310.9
    min: 0
    max: 99999
    step: 0.01
    
        
#### Sensoren   ################################
sensor:
  - platform: template
    sensors:
      zaehlerstand:
        friendly_name: "Zählerstand berechnet"
        unit_of_measurement: "kWh"
        value_template: "{{ (states('input_number.zaehlerstand') | float(0) + states('sensor.deye_total_energy_import') | float(0) -  states('sensor.deye_total_energy_export') | float(0))| round(2) }}"
#### PV Power berechnet ######
## PV1 + PV2 + BKW
  - platform: template
    sensors:
      pv_power_sum_calc:
        friendly_name: "PV Power berechnet (beide Strings + BWK)"
        ## bkw fehlt noch
        unit_of_measurement: "W"
        value_template: "{{ (states('sensor.deye_pv1_power') | float(0) + states('sensor.deye_pv2_power') | float(0) )| round(2) }}"
#### max and daily max power sensors
##### PV1#####
  -   platform: statistics
      name: "PV1 Power Max"
      entity_id: sensor.deye_pv1_power
      state_characteristic: value_max
      max_age:
        days: 9999
  -   platform: statistics
      name: "PV1 Power daily Max"
      entity_id: sensor.deye_pv1_power
      state_characteristic: value_max
      max_age:
        hours: 24
###### PV2 
  -   platform: statistics
      name: "PV2 Power Max"
      entity_id: sensor.deye_pv2_power
      state_characteristic: value_max
      max_age:
        days: 9999
  -   platform: statistics
      name: "PV2 Power daily Max"
      entity_id: sensor.deye_pv2_power
      state_characteristic: value_max
      max_age:
        hours: 24

### pv_power_sum_calc
  -   platform: statistics
      name: "PV total Power Max"
      entity_id: sensor.pv_power_sum_calc
      state_characteristic: value_max
      max_age:
        days: 9999
  -   platform: statistics
      name: "PV total Power daily Max"
      entity_id: sensor.pv_power_sum_calc
      state_characteristic: value_max
      max_age:
        hours: 24